export const GET_TOTAL_WORDS = 'GET_TOTAL_WORDS';
export const SUBMIT_TYPE = 'SUBMIT_TYPE';

export const SUBMIT_DETAILS = 'SUBMIT_DETAILS';
export const UPDATE_INDEX = 'UPDATE_INDEX';
export const UPDATE_MEANING = 'UPDATE_MEANING';
export const UPDATE_MNEMONIC = 'UPDATE_MNEMONIC';
export const UPDATE_SENTENCE = 'UPDATE_SENTENCE';

export const FAILED_WORDS = 'FAILED_WORDS';

export const RANDOM_WORD = 'RANDOM_WORD';